
const data=JSON.parse(document.getElementById('annotation-data').textContent),lang=document.documentElement.lang;const el=id=>document.getElementById(id);let pos=0,answers={};const key='case012-blind-'+data.rubric_sha256;
try{answers=JSON.parse(localStorage.getItem(key)||'{}')}catch{}
function save(){try{localStorage.setItem(key,JSON.stringify(answers))}catch{el('message').textContent=lang==='ko'?'브라우저 저장 실패: JSON을 내보내세요.':'Browser storage failed: export JSON.'}}
function render(){const item=data.items[pos];el('image').src='../'+item.path;el('image').alt=lang==='ko'?'조건을 평가할 생성 이미지':'Generated image to annotate';el('prompt-text').textContent=lang==='ko'?item.korean_display:item.english;el('model-input').textContent=item.english;el('position').textContent=`${pos+1} / ${data.items.length}`;el('constraints').innerHTML='';
for(const c of item.constraints){const f=document.createElement('fieldset'),g=document.createElement('legend');g.textContent=c[lang];f.append(g);const choices=document.createElement('div');choices.className='choices';for(const [v,en,ko] of [['satisfied','Satisfied','충족'],['not_satisfied','Not satisfied','미충족'],['uncertain','Uncertain','판단 불확실']]){const l=document.createElement('label'),r=document.createElement('input');r.type='radio';r.name=c.id;r.value=v;r.checked=answers[item.image_id]?.[c.id]===v;r.addEventListener('change',()=>{(answers[item.image_id]??={})[c.id]=v;save();progress()});l.append(r,document.createTextNode(lang==='ko'?ko:en));choices.append(l)}f.append(choices);el('constraints').append(f)}
el('prev').disabled=pos===0;el('next').disabled=pos===data.items.length-1;progress();}
function progress(){const n=data.items.filter(i=>i.constraints.every(c=>answers[i.image_id]?.[c.id])).length;el('progress').textContent=lang==='ko'?`완료 이미지 ${n}/${data.items.length} · JSON 내보내기를 사용하세요.`:`Complete images ${n}/${data.items.length} · Export JSON to keep a file.`}
el('prev').onclick=()=>{pos--;render()};el('next').onclick=()=>{pos++;render()};el('unrated').onclick=()=>{const n=data.items.findIndex(i=>i.constraints.some(c=>!answers[i.image_id]?.[c.id]));if(n>=0){pos=n;render()}};
el('export').onclick=()=>{const id=el('evaluator').value.trim();if(!id){el('message').textContent=lang==='ko'?'평가자 이름 또는 익명 ID를 입력하세요.':'Enter an evaluator name or anonymous ID.';return}
 const rows=data.items.filter(i=>i.constraints.every(c=>answers[i.image_id]?.[c.id])).map(i=>({image_id:i.image_id,image_sha256:i.image_sha256,values:answers[i.image_id]}));const payload={schema:'case012-annotations-v1',rubric_sha256:data.rubric_sha256,evaluator:{type:'human',id},status:rows.length===data.items.length?'COMPLETE':'PARTIAL',rows,incomplete_image_ids:data.items.filter(i=>!rows.some(r=>r.image_id===i.image_id)).map(i=>i.image_id)};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='case012_annotations.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);el('message').textContent=lang==='ko'?'내보냈습니다. 다운로드된 JSON 파일을 보관하세요.':'Exported. Keep the downloaded JSON file.';};
el('import').addEventListener('change',async()=>{try{const f=el('import').files[0];const x=JSON.parse(await f.text());if(x.schema!=='case012-annotations-v1'||x.rubric_sha256!==data.rubric_sha256)throw Error('schema / rubric mismatch');const map=new Map(data.items.map(i=>[i.image_id,i]));const seen=new Set(),next={...answers};for(const r of x.rows){const i=map.get(r.image_id);if(!i||seen.has(r.image_id)||r.image_sha256!==i.image_sha256)throw Error('image identity mismatch');seen.add(r.image_id);if(Object.keys(r.values).sort().join()!==i.constraints.map(c=>c.id).sort().join()||Object.values(r.values).some(v=>!['satisfied','not_satisfied','uncertain'].includes(v)))throw Error('constraint mismatch');next[r.image_id]=r.values}answers=next;el('evaluator').value=x.evaluator?.id||'';save();render();el('message').textContent=lang==='ko'?'JSON을 가져왔습니다.':'Imported JSON.'}catch(e){el('message').textContent=String(e)}});render();
