
const data=JSON.parse(document.getElementById('viewer-data').textContent),lang=document.documentElement.lang;
const el=id=>document.getElementById(id);
function render(){const pid=el('prompt').value,seed=Number(el('seed').value);const p=data.prompts.find(p=>p.prompt_id===pid);el('prompt-text').textContent=lang==='ko'?p.korean_display:p.english;el('input-text').textContent=p.english;
 const rows=data.rows.filter(r=>r.job.prompt_id===pid&&r.job.seed_label===seed).sort((a,b)=>a.job.setting.loops-b.job.setting.loops);
 el('images').innerHTML='';for(const r of rows){const d=document.createElement('article');d.className='card';const h=document.createElement('h3');h.textContent=`L=${r.job.setting.loops} · S=${r.job.setting.steps}`;d.append(h);const a=document.createElement('a');a.href='../'+r.relative_image_path;const i=document.createElement('img');i.src=a.href;i.alt=`${p.english} / L${r.job.setting.loops}, S${r.job.setting.steps}`;a.append(i);d.append(a);const t=document.createElement('p');t.className='scope';t.textContent=`${r.complete_seconds.toFixed(3)} s · ${(r.peak_allocated_bytes/2**30).toFixed(2)} GiB allocated peak`;d.append(t);const q=document.createElement('p');const score=data.quality?.per_image?.[r.job_id];q.textContent=score?(lang==='ko'?`평가 조건 ${(score.fraction*100).toFixed(1)}% 충족 · 전체 ${score.pass?'충족':'미충족'}`:`Constraints ${(score.fraction*100).toFixed(1)}% satisfied · all ${score.pass?'pass':'not pass'}`):(lang==='ko'?'조건 충족: 미평가':'Constraints: not annotated');d.append(q);el('images').append(d)}
 const u=new URL(location);u.searchParams.set('prompt',pid);u.searchParams.set('seed',seed);history.replaceState(null,'',u);el('language').href=`viewer.${lang==='ko'?'en':'ko'}.html${u.search}${u.hash}`;}
const url=new URL(location),p=url.searchParams.get('prompt'),s=url.searchParams.get('seed');if([...el('prompt').options].some(x=>x.value===p))el('prompt').value=p;if([...el('seed').options].some(x=>x.value===s))el('seed').value=s;
el('prompt').addEventListener('change',render);el('seed').addEventListener('change',render);window.addEventListener('hashchange',()=>{const u=new URL(location);el('language').href=`viewer.${lang==='ko'?'en':'ko'}.html${u.search}${u.hash}`});render();
