"""Measured-only tables, figures and offline explorer; create a new output tree."""
import argparse,sys,json,html
from pathlib import Path
import numpy as np
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from src.core import load,write_new,file_hash

def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--case',type=Path,required=True);p.add_argument('--summary',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();c=a.case;s=load(a.summary);o=a.output
 if o.exists():raise FileExistsError(o)
 if not s['status'].startswith('COMPLETED_'):raise ValueError('No completed measurement to display')
 o.mkdir(parents=True);(o/'figures').mkdir();(o/'demo').mkdir();sel=load(c/'results/raw/selection.json');methods=['INDEPENDENT_4','PAIRWISE_4','INDEPENDENT_8','PAIRWISE_8'];table=['| Budget / method | Removed groups | HELD_OUT median / p95 error |','|---|---|---|']
 for m in methods:
  v=s['local']['HELD_OUT'][m]['relative_error'];table.append(f"| {sel['selections'][m]['budget']}/16 {m.split('_')[0]} | {sel['selections'][m]['removed']} | {100*v['median']:.3f}% / {100*v['p95']:.3f}% |")
 text='\n'.join(table);timing=['| Method | MLP speedup [95% interval] | Model prefill speedup [95% interval] |','|---|---|---|']
 for m in methods:
  vs=[s['timing'][b][m] for b in ['MLP','MODEL_PREFILL']];timing.append('| '+m+' | '+' | '.join(f"{v['speedup_median']:.3f}× [{v['ci95'][0]:.3f}, {v['ci95'][1]:.3f}]" for v in vs)+' |')
 model=['| Method | Correct / 192; regressions / gains / flips | Paired choice NLL change [95% interval] |','|---|---|---|']
 for m in ['B',*methods]:
  v=s['model'][m];n=v['delta_nll'];model.append(f"| {m} | {v['correct']}/192; {v['transitions']['regression']} / {v['transitions']['gain']} / {v['choice_flips']} | {n['mean']:+.5f} [{n['ci95'][0]:+.5f}, {n['ci95'][1]:+.5f}] |")
 pre=f"# Interaction-Aware Structured MLP Pruning\n\nEnglish | [한국어](README.ko.md)\n\nThis controlled Qwen3-0.6B study tested whether signed channel-group interactions improve deletion selection at the same structural budget. The recorded outcome is **{s['status']}**. The two selectors removed different groups at 25%, but the same groups at 50%; the latter is an identical structural choice, not evidence from two different compressed designs. All other layers and BF16 weights outside the sliced layer remain unchanged.\n\n## Held-out reconstruction\n\n{text}\n\nThese are 192 fresh synthetic prompts, layer 13, length 512, with 32 fixed token positions per prompt. They are prompt-level local errors, not downstream accuracy losses.\n\n"
 for b,v in s['transfer'].items():pre+=f"At {int(b)*100/16:g}% deletion, mean paired relative-error change (PAIRWISE minus INDEPENDENT) was **{100*v['mean_paired_relative_error_delta']:+.4f} percentage points**, 95% interval [{100*v['ci95'][0]:+.4f}, {100*v['ci95'][1]:+.4f}]. PAIRWISE had lower error on {v['pairwise_better_prompts']}/{v['n']} prompts.\n\n"
 pre+='![Paired held-out reconstruction comparison](figures/01_transfer.png)\n\n## Model scores and actual cost\n\n'+'\n'.join(model)+'\n\n'+'\n'.join(timing)+'\n\nB is the unpruned BF16 control. Regressions and gains compare against independently computed gold. NLL is conditional on four allowed labels; positive paired change is worse. Task breakdown, Brier, vocabulary KL, label mass and all random baselines are retained in [summary](results/derived/summary.json). Timing uses six fixed prompts and three paired process rounds, with five-call block means. A local MLP speedup is not a model-wide compression ratio.\n\n## What was built\n\nThe harness decomposes one 3072-wide SwiGLU MLP into 16 contiguous groups, estimates a signed 16×16 interaction matrix on 96 calibration prompts, and exhaustively selects deletion sets. It physically slices gate/up rows and down columns. Six smoke prompts and 48 development prompts validate the mapping and arithmetic before held-out access. Twenty fixed random sets per budget show the reference distribution; they do not receive separate model-level runs.\n\nThe chosen-layer width becomes 2304 or 1536, with 25% or 50% fewer MLP parameters. The study neither searches layers nor retrains weights. Selection never uses held-out outcomes. See [methods](METHODS.md), [analysis](ANALYSIS.md) and [limitations](LIMITATIONS.md). Deployment is **NOT_ASSESSED**.\n\n## Inspect and reproduce\n\n- [CPU and GPU instructions](REPRODUCTION.md): scalar reanalysis is separate from hardware replay.\n- [Offline explorer source](demo/index.html): open the local file in a browser; GitHub source preview is not an executing demo.\n- [Protocol](configs/protocol.json), [selection](results/raw/selection.json), [independent audit](provenance/independent_audit.json) and [portfolio](PORTFOLIO.md).\n\nQwen/Transformers supply the model implementation. HOPE motivates interaction-aware deletion in its separate MoE context; no HOPE reproduction or new algorithm is claimed. The project contributes structural surgery, controlled measurements and auditable evidence. OpenAI Codex assisted implementation and analysis. [NOTICE](NOTICE.md) records reuse and licenses.\n'
 (o/'README.md').write_text(pre)
 analysis='# Analysis\n\n'+text+'\n\n## Transfer and selection\n\nThe calibration objectives are different functions, so their optimum values must not be compared directly as if they measured the same cost. The shared quadratic objective below evaluates both choices on the same Q.\n\n'
 q=np.array(sel['Q'])
 for m,v in sel['selections'].items():
  ps=v['removed'];analysis+=f"- {m}: diagonal objective {np.trace(q[np.ix_(ps,ps)]):.6f}; shared pairwise objective {q[np.ix_(ps,ps)].sum():.6f}.\n"
 analysis+='\nThe 50% selectors choose the identical set. A zero paired interval there describes equal recorded computations, not a population non-inferiority study. No new group search was added after this observation.\n\n## All random references\n\nEach of the 20 frozen random sets per budget is evaluated on all 192 held-out prompts. The following distribution is over sets, not 3,840 independent prompts.\n\n'
 for b in [4,8]:
  vals=[s['local']['HELD_OUT'][f'RANDOM_{b}_{i:02d}']['relative_error']['mean'] for i in range(20)]
  analysis+=f"- {b}/16: mean prompt-error across random sets min/median/max {min(vals):.6f}/{np.median(vals):.6f}/{max(vals):.6f}. Random sets beating INDEPENDENT on this mean: {sum(v<s['local']['HELD_OUT'][f'INDEPENDENT_{b}']['relative_error']['mean'] for v in vals)}/20; beating PAIRWISE: {sum(v<s['local']['HELD_OUT'][f'PAIRWISE_{b}']['relative_error']['mean'] for v in vals)}/20.\n"
 analysis+='\n## Gold and model cost\n\n'+'\n'.join(model)+'\n\n'+'\n'.join(timing)+'\n\nHeld-out model comparison measures the complete physically sliced layer, not a masked matrix. Accuracy and local reconstruction are different outcomes. Shared input families and a single model/layer limit transfer claims. All timing intervals are pointwise, not hardware-general guarantees.\n'
 # Post-hoc matrix diagnostics, only called after primary summary exists.
 post={'evidence_kind':'POST_HOC_Q_STABILITY','primary_summary_sha256':file_hash(a.summary),'splits':{}}
 for split,stage in [('CALIBRATION','calibrate'),('DEVELOPMENT','development'),('HELD_OUT','heldout')]:
  rs=[load(f) for f in (c/'results/raw'/stage).glob('c007-*.json')];rs=[r for r in rs if r['split']==split and 'Q' in r];mat=np.mean([r['Q'] for r in rs],axis=0);off=mat[np.triu_indices(16,1)]
  post['splits'][split]={'Q':mat.tolist(),'n':len(rs),'negative_pairs':int((off<0).sum()),'positive_pairs':int((off>0).sum()),'eigenvalues':np.linalg.eigvalsh(mat).tolist(),'relative_Frobenius_change_vs_calibration':float(np.linalg.norm(mat-q)/np.linalg.norm(q))}
 write_new(o/'posthoc_Q.json',post);analysis+='\n## Post-hoc interpretation\n\n[Split-Q stability](results/derived/posthoc_Q.json) was computed only after primary results were fixed. Eigenvalues and signed pair counts describe the recorded matrix; they are not a new selection rule. No held-out oracle, new layer, new pruning budget or recovery training was run.\n';(o/'ANALYSIS.md').write_text(analysis)
 import matplotlib;matplotlib.use('Agg');import matplotlib.pyplot as plt
 plt.rcParams.update({'font.size':10})
 held=[load(f) for f in sorted((c/'results/raw/heldout').glob('*--B.json'))]
 fig,axes=plt.subplots(1,2,figsize=(9,4))
 for ax,b in zip(axes,[4,8]):
  iv=[];pv=[]
  for r in held:
   u={x['method']:x for x in r['local']};iv.append(u[f'INDEPENDENT_{b}']['relative_error']*100);pv.append(u[f'PAIRWISE_{b}']['relative_error']*100)
  ax.scatter(iv,pv,s=12,alpha=.55);lo=min(iv+pv);hi=max(iv+pv);ax.plot([lo,hi],[lo,hi],color='gray',linestyle='--');ax.set_xlabel('Independent local error (%)');ax.set_ylabel('Pairwise local error (%)');ax.set_title(f'{b}/16 removed · 192 held-out prompts')
 fig.tight_layout();fig.savefig(o/'figures/01_transfer.png',dpi=150,metadata={'Software':'Case007'});plt.close(fig)
 fig,ax=plt.subplots(figsize=(6,5));vmax=np.max(abs(q));im=ax.imshow(q,cmap='coolwarm',vmin=-vmax,vmax=vmax);ax.set_xlabel('Group');ax.set_ylabel('Group');ax.set_title('Calibration Q · signed terms, common color scale');fig.colorbar(im,ax=ax,label='Mean output-vector inner product');fig.tight_layout();fig.savefig(o/'figures/02_interactions.png',dpi=150,metadata={'Software':'Case007'});plt.close(fig)
 fig,ax=plt.subplots(figsize=(8,4))
 for b,xoff in [(4,0),(8,1)]:
  vals=[100*s['local']['HELD_OUT'][f'RANDOM_{b}_{i:02d}']['relative_error']['mean'] for i in range(20)];ax.scatter(np.linspace(xoff-.15,xoff+.15,20),vals,label=f'{b}/16 random (20 fixed sets)');
  for m,marker in [('INDEPENDENT','s'),('PAIRWISE','x')]:ax.scatter([xoff],[100*s['local']['HELD_OUT'][f'{m}_{b}']['relative_error']['mean']],marker=marker,s=80,label=f'{b}/16 {m}')
 ax.set_xticks([0,1],['25%','50%']);ax.set_ylabel('Mean prompt relative error (%)');ax.set_title('Held-out random distribution · same 192 prompts per set');ax.legend(fontsize=7);fig.tight_layout();fig.savefig(o/'figures/03_random.png',dpi=150,metadata={'Software':'Case007'});plt.close(fig)
 inputs={r['id']:r for r in load(c/'inputs/HELD_OUT.json')};items=[]
 for r in held:
  for u in r['local']:
   if u['method'] not in methods:continue
   mr=load(c/'results/raw/heldout'/(r['id']+'--'+u['method']+'.json'));items.append({'id':r['id'],'task':r['task'],'method':u['method'],'budget':u['budget'],'removed':u['removed'],'relative_error':u['relative_error'],'transition':mr['transition'],'score':mr['score'],'baseline':r['score'],'prompt':inputs[r['id']]['text'],'cost':s['timing']['MODEL_PREFILL'][u['method']],'source':f"../results/raw/heldout/{r['id']}--{u['method']}.json"})
 encoded=json.dumps({'status':s['status'],'items':items},ensure_ascii=False,allow_nan=False).replace('<','\\u003c')
 page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Case007 evidence explorer</title><style>body{max-width:1000px;margin:auto;padding:20px;font-family:system-ui;line-height:1.5}select,input,button{padding:8px;margin:4px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#eee;padding:12px}img{max-width:100%}</style><h1>Interaction-Aware Structured MLP Pruning</h1><p>Measured HELD_OUT evidence. 192 prompts, repeated methods are not new samples. Local error is not task accuracy. Deployment NOT_ASSESSED.</p><p id="status"></p><label>Task <select id="task"><option value="">All</option><option>RETRIEVAL</option><option>COMPARISON</option><option>CODE</option></select></label><label>Method <select id="method"><option value="">All</option><option>INDEPENDENT_4</option><option>PAIRWISE_4</option><option>INDEPENDENT_8</option><option>PAIRWISE_8</option></select></label><input id="query" placeholder="Find prompt ID" aria-label="Prompt ID"><select id="items" aria-label="Matching items"></select><button id="download">Download visible record</button><pre id="record"></pre><details><summary>Exact prompt</summary><pre id="prompt"></pre></details><img src="../figures/01_transfer.png" alt="Independent versus pairwise held-out local error"><p>Cost shown for a configuration is the six-prompt timing subset, not this individual request.</p><script type="application/json" id="data">'''+encoded+'''</script><script>const d=JSON.parse(document.getElementById('data').textContent), task=document.getElementById('task'),method=document.getElementById('method'),query=document.getElementById('query'),items=document.getElementById('items');let visible=[];document.getElementById('status').textContent=d.status;function show(){const r=visible[items.selectedIndex];document.getElementById('record').textContent=r?JSON.stringify({...r,prompt:undefined},null,2):'No matching records';document.getElementById('prompt').textContent=r?r.prompt:'';}function filter(){visible=d.items.filter(r=>(!task.value||r.task===task.value)&&(!method.value||r.method===method.value)&&r.id.includes(query.value));items.replaceChildren(...visible.map(r=>{const o=document.createElement('option');o.textContent=r.id+' / '+r.method;return o}));show()}for(const x of [task,method,query])x.addEventListener('input',filter);items.addEventListener('change',show);document.getElementById('download').onclick=()=>{const r=visible[items.selectedIndex];if(!r)return;const u=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=r.id+'-'+r.method+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};filter();</script></html>'''
 (o/'demo/index.html').write_text(page);print('Generated measured tables, 3 figures and offline explorer')
if __name__=='__main__':main()
